apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus-https
  namespace: kube-prometheus-stack
spec:
  parentRefs:
  - name: cilium-wildcard-hl-emerconn-com
    namespace: gateway-system
    sectionName: https
  hostnames:
  - prometheus.hl.emerconn.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: kube-prometheus-stack-prometheus
      port: 9090
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus-redirect
  namespace: kube-prometheus-stack
spec:
  parentRefs:
  - name: cilium-wildcard-hl-emerconn-com
    namespace: gateway-system
    sectionName: http
  hostnames:
  - prometheus.hl.emerconn.com
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
