apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus-http
  namespace: kube-prometheus-stack
spec:
  parentRefs:
  - name: cilium-wildcard-hl-emerconn-com
    namespace: gateway-system
  hostnames:
  - prometheus.hl.emerconn.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: kube-prometheus-stack-prometheus
      port: 9090
