apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  chart:
    spec:
      version: "79.7.1"
  values:
    prometheusOperator:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        effect: "NoSchedule"
        operator: "Exists"

    prometheus:
      # annotations:
      # backup.velero.io/backup-volumes: prometheus-kube-prometheus-stack-prometheus-db
      prometheusSpec:
        nodeSelector:
          node-role.kubernetes.io/control-plane: ""
        tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          effect: "NoSchedule"
          operator: "Exists"
        enableFeatures: [ "exemplar-storage" ]
        serviceMonitorSelectorNilUsesHelmValues: false
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: nfs-hot-delete
              accessModes: [ "ReadWriteOnce" ]
              resources:
                requests:
                  storage: 1Gi

    prometheus-node-exporter:
      prometheus:
        monitor:
          enabled: true
          interval: 10s

    nodeExporter:
      enabled: true

    grafana:
      defaultDashboardsTimezone: browser
      persistence:
        enabled: true
        type: sts
        storageClassName: nfs-hot-delete
        accessModes: [ "ReadWriteOnce" ]
        size: 1Gi

    alertmanager:
      enabled: false
