apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: "1h"
    fluxcd.controlplane.io/reconcileArtifactEvery: "10m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  distribution:
    version: "2.x"
    registry: "ghcr.io/fluxcd"
    artifact: "oci://ghcr.io/controlplaneio-fluxcd/flux-operator-manifests"
  components:
  - source-controller
  - kustomize-controller
  - helm-controller
  - notification-controller
  - image-reflector-controller
  - image-automation-controller
  cluster:
    type: kubernetes
    size: small
    multitenant: false
    networkPolicy: true
    domain: "cluster.local"
  kustomize:
    patches:
    - target:
        kind: Deployment
      patch: |
        - op: replace
          path: /spec/template/spec/nodeSelector
          value:
            kubernetes.io/os: linux
        - op: add
          path: /spec/template/spec/tolerations
          value:
            - key: "CriticalAddonsOnly"
              operator: "Exists"
  sync:
    kind: GitRepository
    url: "https://github.com/emerconn/homelab.git"
    ref: "refs/heads/main"
    path: "k8s/flux/clusters/tal-clu-1"
    pullSecret: "flux-system"
