# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secret-sops-webhook-receiver-token.yaml
- flux-instance.yaml
# - webhook-receiver.yaml
- ../../../infra/flux/helm-charts
