# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- aqua.yaml
- cilium.yaml
- cloudflare.yaml
- cloudnative-pg.yaml
- controlplaneio-fluxcd.yaml
- coredns.yaml
- csi-driver-nfs.yaml
- deliveryhero.yaml
- descheduler.yaml
- emberstack.yaml
- external-dns.yaml
- fluent.yaml
- headlamp.yaml
- infisical.yaml
- jetstack.yaml
- kubeclarity.yaml
- metrics-server.yaml
- mongodb.yaml
- node-feature-discovery.yaml
- openobserve.yaml
- opentelemetry.yaml
- piraeus.yaml
- prometheus-community.yaml
- synology-csi-talos.yaml
- tailscale.yaml
- uptime-kuma.yaml
- vmware-tanzu.yaml
- wazuh.yaml
