apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: flux-system
spec:
  chart:
    spec:
      version: "4.12.1"
  dependsOn:
  - name: csi-snapshotter-controller
    namespace: flux-system
  values:
    controller:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        effect: "NoSchedule"
        operator: "Exists"
    storageClasses:
    - name: nfs-cold-delete
      reclaimPolicy: Delete
      allowVolumeExpansion: true
      volumeBindingMode: Immediate
      parameters:
        server: nas-01.hl.emerconn.com
        share: /volume1/nfs-cold-tal-clu-1
      mountOptions:
      - hard
      - nfsvers=4.1
    - name: nfs-cold-retain
      reclaimPolicy: Retain
      allowVolumeExpansion: true
      volumeBindingMode: Immediate
      parameters:
        server: nas-01.hl.emerconn.com
        share: /volume1/nfs-cold-tal-clu-1
      mountOptions:
      - hard
      - nfsvers=4.1
    - name: nfs-hot-delete
      reclaimPolicy: Delete
      allowVolumeExpansion: true
      volumeBindingMode: Immediate
      parameters:
        server: nas-01.hl.emerconn.com
        share: /volume1/nfs-hot-tal-clu-1
      mountOptions:
      - hard
      - nfsvers=4.1
    - name: nfs-hot-retain
      reclaimPolicy: Retain
      allowVolumeExpansion: true
      volumeBindingMode: Immediate
      parameters:
        server: nas-01.hl.emerconn.com
        share: /volume1/nfs-hot-tal-clu-1
      mountOptions:
      - hard
      - nfsvers=4.1
