# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- grafana-dashboard.yaml
- ../../../../../infra/util/node-problem-detector.yaml
patches:
- path: patch.yaml
