# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cilium # TODO: figure out how to add the helmrelease here
- descheduler
- node-feature-discovery
- node-problem-detector
