apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: http
  namespace: gateway-system
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      lbipam.cilium.io/ips: "172.21.0.171"
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    hostname: "*.hl.emerconnelly.com"
    allowedRoutes:
      namespaces:
        from: All
