apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: synology-csi-talos
  namespace: flux-system
spec:
  releaseName: synology-csi-talos
  targetNamespace: synology-csi-talos
  chart:
    spec:
      chart: synology-csi
      sourceRef:
        kind: HelmRepository
        name: synology-csi-talos
        namespace: flux-system
      version: "0.9.4" # synology-csi v1.1.3
  interval: 1h
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values: # https://github.com/zebernst/synology-csi-talos/blob/main/charts/synology-csi/values.yaml
