apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-ext4-retain
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: csi.san.synology.com
parameters:
  csi.storage.k8s.io/fstype: 'ext4'
  location: '/volume1'
reclaimPolicy: Retain
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-ext4-delete
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: csi.san.synology.com
parameters:
  csi.storage.k8s.io/fstype: 'ext4'
  location: '/volume1'
reclaimPolicy: Delete
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-btrfs-retain
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: csi.san.synology.com
parameters:
  csi.storage.k8s.io/fstype: 'btrfs'
  location: '/volume1'
reclaimPolicy: Retain
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-btrfs-delete
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: csi.san.synology.com
parameters:
  csi.storage.k8s.io/fstype: 'btrfs'
  location: '/volume1'
reclaimPolicy: Delete
allowVolumeExpansion: true
