# manually created auth for HCP project 'tal-clu-1'
# https://developer.hashicorp.com/hcp/tutorials/get-started-hcp-vault-secrets/hcp-vault-secrets-kubernetes-vso
apiVersion: v1
kind: Secret
metadata:
    name: hashicorpcloud-serviceprincipal-taloscluster
    namespace: vault-secrets-operator
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: cert-manager
type: Opaque
data:
    clientID: ENC[AES256_GCM,data:KIy6i4SoPHf7CRH617zdWXU696dsJrzrUrcGw0Yxtduar6OrO/a8UJW0CbY=,iv:S6UBsrmwGCHQiKTbf1WGeY72YGKrIY867iBEDPnf//4=,tag:9xDMsbXDsxtCYfA7tAFWKA==,type:str]
    clientSecret: ENC[AES256_GCM,data:J0kqLKa9aQg9p368az4pRryKu+6hng0xrx4ciQyRblFkWC3Zg1/Z/gVhYIG1YMvLqvQwiZ+vCFzwDoDNNsvN/vyfOQfA4wzs1MdQbdnoKnQQtTxn7DU6cw==,iv:E02oKI+GtxhkhuFlPTrurbnWBqBRqylm+RxFGyqU6T8=,tag:e8r9S3vsqWylsDPr9qfl9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
      - recipient: age1q4s78mspzd665gj4tavetnwqym7zc8vx0fr3qj203saeldg223rqwzakhu
        enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBES1ZRWkFBMlZvQUllOFJP
            QmFyR1gxK2ZaNHdjNzVGT3FzeWRUTklVR1VjCjFuWE1aeW4zdVd2YUk2Q2djbXlw
            TFQ5bUtXN3dJekI4THZ5ZkIxOXFJRGMKLS0tIDMxdU90Qzl3bVY0aXdzSVZ1SHEr
            VTRwQ0xWMGFkU01pVTE5NVprYnNCV2cKdw83xeDhlVybBQ07pMx3FDKuTWonGoNd
            Ve/ax3ZXI2108QMtWat/6C1Gl5EcnCDDzR7FfWO+L0qiPhFZEW370g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-17T03:51:46Z"
    mac: ENC[AES256_GCM,data:NGLRBE0tTa5NDN9kRM42liTiWFGyzFRnDGe39+mdXsvytUc41gVuqa3EsGr1Dt306ewxqAOTrXrtB6IGMlcwyaz1rvCePdKod187uda6178cs/wMVNMuQauCw7vLAE2JcyTOPdHnQd39G3yFajTPbRNbhaOW/qyWOWsCkU9abW0=,iv:C8uY96jzfjt8jRYQP0t076QYgAeMHdkHQDcZ75LmjNs=,tag:3u4B430Hqqf7mV01HdXfpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
