apiVersion: v1
kind: ServiceAccount
metadata:
  name: infisical-token-reviewer
secrets:
- name: infisical-token-reviewer-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: infisical-token-reviewer-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: infisical-token-reviewer
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: infisical-token-reviewer-token
  annotations:
    kubernetes.io/service-account.name: "infisical-token-reviewer"
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: infisical-service-account
