# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../../infra/secrets/infisical-operator.yaml
- secret-sops-service-token.yaml
- k8s-auth.yaml
- test-secret.yaml
patches:
- path: patch.yaml
