# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../../infra/secrets/infisical-operator.yaml
- secret-sops-service-token.yaml
- service-account.yaml
- cluster-role-binding.yaml
- secret.yaml
patches:
- path: patch.yaml
