apiVersion: v1
kind: Secret
metadata:
    name: service-token
    namespace: infisical-operator
type: Opaque
data:
    infisicalToken: ENC[AES256_GCM,data:p59QeoEISDS02pSZ/U/HIgBW1xXSZU0f5w6OoOKa83W8DLzUg7RwobY1hYujyrQSV2S3XSn21m7vluyEIpJJHye58Z9btC2/Jt0W0522DU7yw20+wyibX+gHd/goU/KZ2F1KsD68SZ4HbP8a8D0P3ozG7K6u2b+VIFb35HYeYXQXVmK9tzDkbUJwDuw=,iv:AMxCosyDgNtatlRsM+huMJs8RV6nyf4pSoakgHo7QHQ=,tag:f1S/OIdtoYj6y0oykBukVQ==,type:str]
sops:
    age:
        - recipient: age1q4s78mspzd665gj4tavetnwqym7zc8vx0fr3qj203saeldg223rqwzakhu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbXdEMmRSbVJhekxGZlQ3
            UEEzQjFKalZoSE92dkRyNTdRSXFUbm9JSnlnCmlvdGRqTVFkWTlCNzFiSC9CZXNE
            ZHVGdzZ3Qm9rdXVsenNZclpmMXg2WTAKLS0tIGxkWWFDWm5PTDk0YmNLS29uNmk4
            MnVwUzZnemJDYnF3Vk13YjBOQnkvRDgKC8CXgFruip8sxKofv4LIkjY4orkOq0Wc
            RW4jh/r6Bmc0GyIPpVqN9LLZvwJwRmFWvY0drOlJrdr9hCHZGhbhTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-20T22:55:46Z"
    mac: ENC[AES256_GCM,data:4L7RiG0+6Qsp+HWRBpx2uot+HAR0ps6jIIcx+2iXuGgt6Hag0fbzFFz8MKomJx7s3Pf86wu8QFWA2CXavVgAjnbNDzCCZZWrDdFen8woWiFQhzftyMBYrhPdN8FwCFVk03rufGahl6JoUxiV80rmYtaUOHBd/AkWHx3OuP0GRSs=,iv:eSYbH6pn+zir1DPkv3lQ6aZchoe0eikpailuI18eCJw=,tag:0VXySjMaRaejd1aTaitseA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
