apiVersion: v1
kind: Secret
metadata:
    name: universal-auth
    namespace: infisical-operator-system
type: Opaque
stringData:
    clientId: ENC[AES256_GCM,data:n+9Fl5FgjnJLxjnCpS7fYIlZJy/Bl/vaHgD2Ucpj83MYjoSY,iv:4Hx+IfrCPYyTL5/SXwUygG304pJR13taa4D67Bz2nhE=,tag:rWid6uOlopR3bx5jpI7syQ==,type:str]
    clientSecret: ENC[AES256_GCM,data:A2CIS2OCANuWbKFC/kdrUo97gpkhrJbyQz7wvSKp6a7nAY3K+AV7As6YjI+kptktksloToyuiS81uyTI2ELE3w==,iv:kJwxZdpUbxR6uSyKr4FvUUqI0bmqtkmdMo1O4vkrY7M=,tag:M1wLqYsP91Yl1cUCbeLKjw==,type:str]
sops:
    age:
        - recipient: age1q4s78mspzd665gj4tavetnwqym7zc8vx0fr3qj203saeldg223rqwzakhu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbXdEMmRSbVJhekxGZlQ3
            UEEzQjFKalZoSE92dkRyNTdRSXFUbm9JSnlnCmlvdGRqTVFkWTlCNzFiSC9CZXNE
            ZHVGdzZ3Qm9rdXVsenNZclpmMXg2WTAKLS0tIGxkWWFDWm5PTDk0YmNLS29uNmk4
            MnVwUzZnemJDYnF3Vk13YjBOQnkvRDgKC8CXgFruip8sxKofv4LIkjY4orkOq0Wc
            RW4jh/r6Bmc0GyIPpVqN9LLZvwJwRmFWvY0drOlJrdr9hCHZGhbhTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-22T17:54:38Z"
    mac: ENC[AES256_GCM,data:6A4b61YzTAXz6uWwTMewgoQtzirabFZuSPiGLwYXmUT1OmoKmZvdUR+3hhFvoFDvGcjRENMWT5UpV69wQEc3zNdRLM8pESXnALElylmwu68MScDxUKQRjJm8sSDwg2JYI6bXmG00Z1jDnqVRvw0yXS3vCxCZEcBvbbMMuqcs53k=,iv:snd/PjCx3xmtQJkb7pn+S0hIBdpEoIm8bIjduATqwS8=,tag:coHAkL7liFr5s/a3cB2T4g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
