apiVersion: v1
kind: Secret
metadata:
    name: service-token
    namespace: infisical-operator-system
type: Opaque
data:
    infisicalToken: ENC[AES256_GCM,data:p59QeoEISDS02pSZ/U/HIgBW1xXSZU0f5w6OoOKa83W8DLzUg7RwobY1hYujyrQSV2S3XSn21m7vluyEIpJJHye58Z9btC2/Jt0W0522DU7yw20+wyibX+gHd/goU/KZ2F1KsD68SZ4HbP8a8D0P3ozG7K6u2b+VIFb35HYeYXQXVmK9tzDkbUJwDuw=,iv:AMxCosyDgNtatlRsM+huMJs8RV6nyf4pSoakgHo7QHQ=,tag:f1S/OIdtoYj6y0oykBukVQ==,type:str]
sops:
    age:
        - recipient: age1q4s78mspzd665gj4tavetnwqym7zc8vx0fr3qj203saeldg223rqwzakhu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbXdEMmRSbVJhekxGZlQ3
            UEEzQjFKalZoSE92dkRyNTdRSXFUbm9JSnlnCmlvdGRqTVFkWTlCNzFiSC9CZXNE
            ZHVGdzZ3Qm9rdXVsenNZclpmMXg2WTAKLS0tIGxkWWFDWm5PTDk0YmNLS29uNmk4
            MnVwUzZnemJDYnF3Vk13YjBOQnkvRDgKC8CXgFruip8sxKofv4LIkjY4orkOq0Wc
            RW4jh/r6Bmc0GyIPpVqN9LLZvwJwRmFWvY0drOlJrdr9hCHZGhbhTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-20T22:56:47Z"
    mac: ENC[AES256_GCM,data:vlo7v7Xp4zLO9mqgD70MPzUnTpoFIxZKVj/gelEvIoGS3yuwbsGCvFPb87yHg4o9p4HeCfZrKJUNo93jBz89WVcZs/7ni8OGIoNI0cK6OTauM50x8UiEEhstsnhqlpOCm29+aS7p6tB8y+68YXoDValcDWS+ZwLiB4WkVdEhTKg=,iv:qU9uSD+rogs/21fPuZB0QxEL61xZyZU4NN7ZM8FOLUs=,tag:2OER4fJtiPJgckDtvJN2QA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
