apiVersion: v1
kind: Secret
metadata:
    name: service-token
    namespace: infisical-operator
type: Opaque
data:
    infisicalToken: ENC[AES256_GCM,data:PuR9qrbwo69ieeRqA/gaQaIcwG2IszS/GX3ACjyiN51Dt6721OlvY65bLLT6FbUf8Dnk4VbGIWz5hRMqqeivSeWMLkdTe18Q8YOmM8YMgdI3L+fdXmu+gXImEXHmnjObSciqhrx2EaqW,iv:7JLVeRr5UlWBdQptkkjPVS8/3RzPou/8VCvSIuZOeYQ=,tag:yX9JQmq7iIpNphHzvfKB/Q==,type:str]
sops:
    age:
        - recipient: age1q4s78mspzd665gj4tavetnwqym7zc8vx0fr3qj203saeldg223rqwzakhu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbXdEMmRSbVJhekxGZlQ3
            UEEzQjFKalZoSE92dkRyNTdRSXFUbm9JSnlnCmlvdGRqTVFkWTlCNzFiSC9CZXNE
            ZHVGdzZ3Qm9rdXVsenNZclpmMXg2WTAKLS0tIGxkWWFDWm5PTDk0YmNLS29uNmk4
            MnVwUzZnemJDYnF3Vk13YjBOQnkvRDgKC8CXgFruip8sxKofv4LIkjY4orkOq0Wc
            RW4jh/r6Bmc0GyIPpVqN9LLZvwJwRmFWvY0drOlJrdr9hCHZGhbhTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-20T22:53:17Z"
    mac: ENC[AES256_GCM,data:IJlaTM4Ju3yNOxT2irg0jOp3GJxs3dCZV/3CZAKfyeee5+sF+UNO6z6jTueEiW+ZQRdhg0WKFX7yIqiKRsjnmAXyLrgA+8F9RlVcn6pF9dum8W/EpE2KnN8mfVA+rIpNf/W0Of5Cx4qxZm6VyPrYBeA5+3tK4c90AWu1A3a2KLA=,iv:/g1ab8AlHUMxmAmkMmAPbw2KRJsjjVPklOlPx8wm3PU=,tag:gt6AugJGFp+NvEUySz4MFA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
