apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: infisical-token-reviewer-token
  namespace: infisical-operator-system
  annotations:
    kubernetes.io/service-account.name: "infisical-token-reviewer"
