apiVersion: v1
kind: Secret
metadata:
    name: adguard-config
    namespace: external-dns
type: Opaque
stringData:
    url: ENC[AES256_GCM,data:qqcW8x8qkhZQgcVU/4br4ow=,iv:cjBFeZMWkeTOwCGFQS2aJFVPoi8zCf7mMEXRS/xZCvI=,tag:8n5avLTkQUI7umYuyM5/Vw==,type:str]
    user: ENC[AES256_GCM,data:ynUcojc=,iv:pBgbbfwqNyjUK67CLzS4Bkz3PlWjfH/1B7FWOOLslUA=,tag:aZj0eIXJ19BQgmJWRtp7aA==,type:str]
    password: ENC[AES256_GCM,data:0VZkvI5g/7OuumbCRTI=,iv:rocfAbfhw+x76Vt+b/glPt7a2nhoz0gYmOK5zuc5Zxo=,tag:UuHKD2cmw3Fk4CRsAR8vKA==,type:str]
sops:
    age:
        - recipient: age1q4s78mspzd665gj4tavetnwqym7zc8vx0fr3qj203saeldg223rqwzakhu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SmgxYWhXMllWMGNxTzFm
            NWRiUnJEbWlBVisrYkpQN2p4eEhLaGVKM0RZCjB3eEFkdlU5cTI2U1N4Y2RsY2VF
            UFNEWmhaODdHc29yTUtSUXVKWHlLK2cKLS0tIHc3aHBvaGlsZTBuM2o2MHp1NWll
            R294VTZIY1pQWFJjZ3hYSWl1eWxzcnMKXoSlKS8vAd9Gdq8/pMbSbRWlCLUW1xHb
            HUmY0YYVQObAf83GBsWL3oBJ9fd0icb+dfHbpiXWrTxLRvqFqFK++g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T06:52:17Z"
    mac: ENC[AES256_GCM,data:4hW63E7Gq0f5XOhTb1MGgXuYKk/kJB0HLioVc2UBgRkN3+UaMWKYnrjn7YjmMBrfk9cFlG5OfCmJTljd2I8OQi3eQaCH5hcf1diL9ev/i0nHeO9cZSE/P/ZnSFr2BW+GIIzYmINcZVLCl+Q5EgwQH3u2hZ4nJC2MQHocfsf3f2Q=,iv:Bt0UqPKyWpvKYff5ManAr9lRRBboq1fG6glXf+vufKk=,tag:OHTQsmL8C1BUNe0JRg0p6A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
