# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- aqua.yaml
- cilium.yaml
- cloudflare.yaml
- cloudnative-pg.yaml
- deliveryhero.yaml
- descheduler.yaml
- emberstack.yaml
- external-secrets.yaml
- fluent.yaml
- hashicorp.yaml
- headlamp.yaml
- ingress-nginx.yaml
- jetstack.yaml
- kubeclarity.yaml
- kubernetes-dashboard.yaml
- metrics-server.yaml
- minio-operator.yaml
- minio.yaml
- mongodb.yaml
- nfs-subdir-external-provisioner.yaml
- node-feature-discovery.yaml
- openobserve.yaml
- opentelemetry.yaml
- piraeus.yaml
- prometheus-community.yaml
- rook-release.yaml
- synology-csi-talos.yaml
- tailscale.yaml
- traefik.yaml
- uptime-kuma.yaml
- vmware-tanzu.yaml
