# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - synology-dsm-proxy.yaml
- secret-sops-clients.yaml
- ../../../../../infra/storage/synology-csi-talos
patches:
- path: patch.yaml
