apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: synology-csi-talos
  namespace: flux-system
spec:
  chart:
    spec:
      version: "0.9.5-pre.4" # synology-csi:v1.2.0
  values:
    node:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        effect: "NoSchedule"
        operator: "Exists"
    storageClasses:
      synology-iscsi-storage:
        disabled: true
    volumeSnapshotClasses:
      synology-snapshotclass:
        disabled: true
