apiVersion: v1
kind: Secret
metadata:
    name: clients
    namespace: synology-csi-talos
type: Opaque
stringData:
    client-info.yml: ENC[AES256_GCM,data:0l87wf926UhSYz5Q8nFaOy50EY+UB8tKRS8pvUW89Nhy06c8PPeJ9nrFgi4ImdNWu1HCbdehgFgWpL7poVtLY19Y/Met3cnMWyuprjA+G2ZFhVTfwuVrtMeSCc9sdDhZPKCOUZ9yCIsfZHB6cg==,iv:K4N4hNMaqjaV5+FPrlAVSYsOzjdLArwfNd45K+PKd7A=,tag:i2Jk/okGiGjHw2t6qxr/cQ==,type:str]
sops:
    age:
        - recipient: age1q4s78mspzd665gj4tavetnwqym7zc8vx0fr3qj203saeldg223rqwzakhu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUlo1b1QxZDVYREwrYWdS
            YmhOaW9hNVNoM0YzdVFLWmpoMDdZTm9WZ3lJCkJnQXVPelFsdisyY1d6MzZqRkds
            VXdkcTY2SmRpRmNnWll3Tk1XWlI5ZUEKLS0tIEsxNmc0bmNleFN5ek0yRVo0TWVs
            QzVYWGV5K25ZL3VCeGxiU2ppZW9iTXcK8iRkFU9ob6g7n76TP+luSz17UAhCsegb
            UBWw2dyaXEtI/p4RJNOlnrlLdZYXVWb1zq+MeixdRJSsf6f2TCXw2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T03:44:58Z"
    mac: ENC[AES256_GCM,data:MzG3ZDl+SXazpHs5mvw0tr3ZVUgOXLRM+mX3p8mzjESsBvQBA4QE4jJ7wZWvenyKX5J1Myo5wozkOTAgMNWlc3bR8hv6egaTVG7lwObQVojYGDA3EUA+tYrrh/WEw1nUNo3qf6RMu/S6XLnxWdkrRyEmGA5AoT1NqEoOnonBasw=,iv:mlMFkIbjrJKvYDkjZPm1I9Mcl7sSaUREAiOyFtH6tbc=,tag:xseB99mDmJjT2/5c8YbDJw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
