apiVersion: v1
kind: Secret
metadata:
    name: clients
    namespace: synology-csi-talos
type: Opaque
stringData:
    client-info.yml: ENC[AES256_GCM,data:odySF2MLklAaY2wAAly0AI3xTpZCno+UnGxTliuwYHMqo3rqPoSAs9D6VMpd0rQatTj9AGq75PE8hA33D75hVWWWDgt4u/ZEyOqA72+pSBkNZVhVRvGdGhR2DQI0wRjRt7Y1MQAUT6fXhQ==,iv:BoGvfKfiWxr/cg0tbZk5OmATLtUmPBDSqnL2KkroBNQ=,tag:/0/XuNX10fnh9Quumc9TuQ==,type:str]
sops:
    age:
        - recipient: age1q4s78mspzd665gj4tavetnwqym7zc8vx0fr3qj203saeldg223rqwzakhu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUlo1b1QxZDVYREwrYWdS
            YmhOaW9hNVNoM0YzdVFLWmpoMDdZTm9WZ3lJCkJnQXVPelFsdisyY1d6MzZqRkds
            VXdkcTY2SmRpRmNnWll3Tk1XWlI5ZUEKLS0tIEsxNmc0bmNleFN5ek0yRVo0TWVs
            QzVYWGV5K25ZL3VCeGxiU2ppZW9iTXcK8iRkFU9ob6g7n76TP+luSz17UAhCsegb
            UBWw2dyaXEtI/p4RJNOlnrlLdZYXVWb1zq+MeixdRJSsf6f2TCXw2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T03:50:30Z"
    mac: ENC[AES256_GCM,data:jkvsmawRUQ9QZbkIiaJVsXDP9E4iP6M8yNrwH6gbk5hnJ40Y/CEYw6/8YjAFJ4FJLvp2O6fd/8F0Xtbew9Kv9I3aaZ+J+SxrInzbElMdIoBSe1o93Vbdwr6BR2YciJgRek0kJjVyaaGFxb1KuUpv3uKhqVe8ZxUWXzI1YwaS+NI=,iv:yTu2vEVmqrgZFG+e5ZczXb92mjJ/XJlY/yMaZ2BaMr0=,tag:OFaHQ2Er1CzMsWfqyTl0rA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
