apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-snapshotter-controller
  namespace: flux-system
spec:
  releaseName: csi-snapshotter-controller
  targetNamespace: kube-system
  chart:
    spec:
      chart: snapshot-controller
      sourceRef:
        kind: HelmRepository
        name: piraeus
        namespace: flux-system
  interval: 1h
  install:
    remediation:
      retries: -1
  values:
    # https://github.com/piraeusdatastore/helm-charts/blob/main/charts/snapshot-controller/values.yaml
    # TODO: add CRDs from Git source, helm chart doesn't manage these
    # https://github.com/kubernetes-csi/external-snapshotter/tree/master/client/config/crd
