apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: external-snapshotter
  namespace: flux-system
spec:
  interval: 24h
  url: https://github.com/kubernetes-csi/external-snapshotter.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: csi-snapshotter-crds
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: external-snapshotter
    namespace: flux-system
  path: ./client/config/crd
  wait: true
  prune: true
  timeout: 2m
  interval: 1h
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wrapper-helm-csi-snapshotter-controller
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./controller.yaml"
  prune: true
  wait: true
  dependsOn:
  - name: csi-snapshotter-crds
