apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: external-snapshotter
  namespace: flux-system
spec:
  interval: 24h
  url: https://github.com/kubernetes-csi/external-snapshotter.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: csi-snapshotter-crds
  namespace: flux-system
spec:
  interval: 1h
  prune: true
  sourceRef:
    kind: GitRepository
    name: external-snapshotter
    namespace: flux-system
  path: ./client/config/aasdfasdf
  wait: true
  timeout: 2m
