apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: csi-snapshotter-crds
  namespace: flux-system
spec:
  interval: 1h
  prune: true
  sourceRef:
    kind: GitRepository
    name: csi-snapshotter
    namespace: flux-system
  path: ./client/config/crd
  wait: true
  timeout: 2m
