apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: github_kubernetes-csi_external-snapshotter
  namespace: flux-system
spec:
  interval: 24h
  url: https://github.com/kubernetes-csi/external-snapshotter.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: csi-snapshotter-crds
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: external-snapshotter
    namespace: flux-system
  path: ./client/config/asdf
  wait: true
  prune: true
  timeout: 2m
  interval: 1h
