apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: csi-snapshotter
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/flux/infra/storage/csi-snapshotter
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
  - name: csi-snapshotter-crds
    namespace: flux-system
