apiVersion: v1
kind: Namespace
metadata:
  name: infisical-operator-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infisical-operator
  namespace: flux-system
spec:
  releaseName: controller-manager
  targetNamespace: infisical-operator-system
  chart:
    spec:
      chart: secrets-operator
      sourceRef:
        kind: HelmRepository
        name: infisical
        namespace: flux-system
  interval: 1h
  install:
    remediation:
      retries: -1
  values: # https://github.com/Infisical/infisical/blob/main/helm-charts/secrets-operator/values.yaml
