apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wazuh
  namespace: flux-system
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: wazuh
        namespace: flux-system
      chart: wazuh
      version: "1.0.7"
  values:
    agent:
      enabled: true
      joinManager:
        managerHost: "wazuh.wazuh.svc.cluster.local"
        workerHost: "wazuh-manager-worker.wazuh.svc.cluster.local"
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        effect: "NoSchedule"
        operator: "Exists"

    dashboard:
      replicas: 1
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        effect: "NoSchedule"
        operator: "Exists"

    indexer:
      replicas: 1
      storageSize: 1Gi
      storageClass: synology-ext4-retain
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        effect: "NoSchedule"
        operator: "Exists"

    master:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        effect: "NoSchedule"
        operator: "Exists"

    worker:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        effect: "NoSchedule"
        operator: "Exists"

    wazuh:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        effect: "NoSchedule"
        operator: "Exists"

      master:
        storageSize: 1Gi
        storageClass: synology-ext4-retain

      worker:
        replicas: 1
        storageSize: 1Gi
        storageClass: synology-ext4-retain
