apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wazuh
  namespace: flux-system
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: wazuh
        namespace: flux-system
      chart: wazuh
      version: "1.0.4"
  values:
    indexer:
      storageSize: 1Gi
      storageClass: synology-ext4-retain
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        effect: "NoSchedule"
        operator: "Exists"

    wazuh:
      master:
        storageSize: 1Gi
        storageClass: synology-ext4-retain
        nodeSelector:
          node-role.kubernetes.io/control-plane: ""
        tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          effect: "NoSchedule"
          operator: "Exists"

      worker:
        storageSize: 1Gi
        storageClass: synology-ext4-retain
        nodeSelector:
          node-role.kubernetes.io/control-plane: ""
        tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          effect: "NoSchedule"
          operator: "Exists"
