apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-crds-experimental
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: kubernetes-sigs-gateway-api
  path: "./config/crd/experimental"
  interval: 1h
  prune: true
