apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubernetes-sigs-gateway-api
  namespace: flux-system
spec:
  url: https://github.com/kubernetes-sigs/gateway-api
  ref:
    tag: v1.2.1
  interval: 24h
