# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - csi-driver-nfs
- csi-snapshotter
# - minio-operator
# - minio-tenant
# - rook-ceph-cluster
# - rook-ceph-operator
# - rook-ceph-test-buckets
# - snapshot-controller
# - synology-csi-talos
# - velero
