[book]
title = ""
description = "homelab"
authors = ["Emerson Connelly"]
language = "en"
multilingual = false
src = "src"

[output.html]
git-repository-url = "https://github.com/emerconnelly/homelab"
git-repository-icon = "fa-github"
git-branch = "main"
default-theme = "ayu"
preferred-dark-theme = "ayu"
no-section-label = true

[output.html.fold]
enable = false
level = 1

[output.html.search]
limit-results = 15

[output.html.playground]
editable = true
line-numbers = true
