# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- http-route.yaml
- service-account-token.yaml
- ../../../../../infra/observe/headlamp.yaml
patches:
- path: patch.yaml
