apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: service-account-token
  namespace: headlamp
  annotations:
    kubernetes.io/service-account.name: headlamp

# To get the token:
# kubectl get secret -n headlamp service-account-token -o jsonpath='{.data.token}' | base64 -d
