apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: eraser
  namespace: flux-system
spec:
  chart:
    spec:
      version: "1.3.1"
  values:
    deploy:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        effect: "NoSchedule"
        operator: "Exists"
    runtimeConfig:
      components:
        scanner:
          enabled: false
