# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - cluster-issuer.yaml
# - hcp-vault-secrets-app.yaml
- ../../../../../infra/util/cert-manager.yaml
- secret-sops-cloudflare-api-token.yaml
patches:
- path: patch.yaml
