apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-Token: ENC[AES256_GCM,data:5iQmVR650WEOkgTnXAA52IlRJXRsYqs/tnnX2F2XbHBDVVOUBZmeuA==,iv:vlJnPYj3vdrFFBDlh31fjffaV9D4afo/LlBWT+VtszA=,tag:bq/HccICSjRbUYbgwn5UhQ==,type:str]
sops:
    age:
        - recipient: age1q4s78mspzd665gj4tavetnwqym7zc8vx0fr3qj203saeldg223rqwzakhu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Y2gwdjhKNjZhUTQ1QXlY
            Zm9EbnE4dmNGaUpXbHJ1aUFlQUhLdWU2VVJVCitUMUwvOGc4UGk3YTdITzJ6cmFY
            R3hjcUNDNTlFNEJvaFQrcFZoMjhoaVkKLS0tIEZNVERCVlBSRHFDbmlnVjdrQ2ZS
            Y2NQYUJlcUlMMVBjNktwRlZUbjhJTmcKCX80uN4jI+5qPFnmSuoSh4JkZCvUzI7Y
            DjPpASjvVT36JLXA8Wx2WObiC7ANrDRAAl82zyi4INthPxLnDge5/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T00:31:48Z"
    mac: ENC[AES256_GCM,data:krMGVnomVLPpEkQ1t1Qi8wddi6kReDC7bqZMOijP/40i0J9soq2/UCvBg1fKeR/BvmbthsOHqBw2J56W8LWGqUn0sV2jkuYa25W0vlmTaeMnaOy/MEz5MG7UNf7CMLJjqBySs/qqIGfNahGM2V1U674z0TlqXVUbBXR3iSy+AJE=,iv:4e41PUSVhiBgj7Nc/DKljRXcdWHePMK/0kpoLtFp/DM=,tag:cWf71Bmc+VRla2CbEN8uSg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
