apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:Va25zM1QdHIQjJCghZ8qfF6B1UISV3CvITLNtu+V+4pbcYXMerVtOw==,iv:1TuXuySOs17ivxMEUrg1puBSZc2ouSzS3gPaYNGDEm8=,tag:emGCGp+7/O58OXfGr5VqPA==,type:str]
sops:
    age:
        - recipient: age1q4s78mspzd665gj4tavetnwqym7zc8vx0fr3qj203saeldg223rqwzakhu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Y2gwdjhKNjZhUTQ1QXlY
            Zm9EbnE4dmNGaUpXbHJ1aUFlQUhLdWU2VVJVCitUMUwvOGc4UGk3YTdITzJ6cmFY
            R3hjcUNDNTlFNEJvaFQrcFZoMjhoaVkKLS0tIEZNVERCVlBSRHFDbmlnVjdrQ2ZS
            Y2NQYUJlcUlMMVBjNktwRlZUbjhJTmcKCX80uN4jI+5qPFnmSuoSh4JkZCvUzI7Y
            DjPpASjvVT36JLXA8Wx2WObiC7ANrDRAAl82zyi4INthPxLnDge5/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T00:34:07Z"
    mac: ENC[AES256_GCM,data:rxNZHyfzrp6CJ9RGTZcr5kiUJJvazs7i01cB40HgdUNMUSPca9kNz8bDIkDLVJ5//MW9s89gY8h9ec18kNuyZBBQ56Vm+u0SqD+ivPW0KvLkucYpzDp3si/Awu1zczXjkcEP9GlOI+m2OZ+oSDqO/EgnsObgyodg0d0sy448XL4=,iv:1I9UClyVeqQFFUg83hp9GMgyy9tlcOfWQeDHFt6VWx0=,tag:kJsL2F7XJQ1Ui5Jg+px6IA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
