apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-wildcard-hl-emerconn-com
  namespace: gateway-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01-emerconn-com
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      lbipam.cilium.io/ips: "172.21.0.171"
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    hostname: "*.hl.emerconn.com"
    allowedRoutes:
      namespaces:
        from: All
  - name: https
    protocol: HTTPS
    port: 443
    hostname: "*.hl.emerconn.com"
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: wildcard-hl-emerconn-com-tls
    allowedRoutes:
      namespaces:
        from: All
