apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubernetes-csi-external-snapshotter
  namespace: flux-system
spec:
  ref:
    tag: v8.4.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-snapshotter-controller
  namespace: flux-system
spec:
  chart:
    spec:
      version: "4.2.0"
  values:
    controller:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        effect: "NoSchedule"
        operator: "Exists"
      serviceMonitor:
        # TODO: create Grafana dashboard
        create: false
