apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: descheduler
  namespace: flux-system
spec:
  chart:
    spec:
      version: "0.34.0"
  values:
    kind: CronJob
    schedule: "*/10 * * * *"
    serviceMonitor:
      # TODO: create Grafana dashboard
      enabled: false
      namespace: kube-system
